services:
  postgres:
    image: pgvector/pgvector:pg16
    container_name: quizsense_postgres
    environment:
      POSTGRES_DB: quizsense
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data:
