# Generated by Django 6.0.3 on 2026-03-11 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="uploadedfile",
            name="summary",
            field=models.TextField(blank=True),
        ),
    ]
