# Generated by Django 6.0.3 on 2026-04-24 17:16

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0003_textbookchunk_uploadsession_uploadedchunk_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="textbookchunk",
            name="embedding",
            field=pgvector.django.vector.VectorField(dimensions=768),
        ),
        migrations.AlterField(
            model_name="uploadedchunk",
            name="embedding",
            field=pgvector.django.vector.VectorField(dimensions=768),
        ),
    ]
