# Generated by Django 6.0.3 on 2026-04-24 18:07

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0004_alter_textbookchunk_embedding_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="textbookchunk",
            name="embedding",
            field=pgvector.django.vector.VectorField(dimensions=1536),
        ),
        migrations.AlterField(
            model_name="uploadedchunk",
            name="embedding",
            field=pgvector.django.vector.VectorField(dimensions=1536),
        ),
    ]
