# Generated by lazyLiza on 2026-04-25
# Change embedding dimensions from MiniMax embo-01 (1536)
# to sentence-transformers/all-MiniLM-L6-v2 (384)

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0005_alter_textbookchunk_embedding_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="textbookchunk",
            name="embedding",
            field=pgvector.django.vector.VectorField(dimensions=384),
        ),
        migrations.AlterField(
            model_name="uploadedchunk",
            name="embedding",
            field=pgvector.django.vector.VectorField(dimensions=384),
        ),
    ]
