# Generated by lazyLiza on 2026-04-25
# Part 2: Create TextbookChunk and UploadedChunk with JSON text embeddings
# (replaces old pgvector VectorField with JSON + numpy cosine similarity).

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0007a_create_uploadsession"),
    ]

    operations = [
        migrations.CreateModel(
            name="TextbookChunk",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("source_title", models.CharField(max_length=255)),
                ("chunk_index", models.PositiveIntegerField()),
                ("content", models.TextField()),
                ("embedding", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "chapter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="textbook_chunks",
                        to="quiz.chapter",
                    ),
                ),
                (
                    "topic",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="textbook_chunks",
                        to="quiz.topic",
                    ),
                ),
            ],
            options={
                "ordering": ["chapter__number", "source_title", "chunk_index"],
            },
        ),
        migrations.CreateModel(
            name="UploadedChunk",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("chunk_index", models.PositiveIntegerField()),
                ("content", models.TextField()),
                ("embedding", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "chapter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="uploaded_chunks",
                        to="quiz.chapter",
                    ),
                ),
                (
                    "uploaded_file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chunks",
                        to="quiz.uploadedfile",
                    ),
                ),
                (
                    "upload_session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chunks",
                        to="quiz.uploadsession",
                    ),
                ),
            ],
            options={
                "ordering": ["upload_session_id", "uploaded_file_id", "chunk_index"],
            },
        ),
    ]
