# Generated by lazyLiza on 2026-04-25
# Part 1: Create UploadSession model (needed by TextbookChunk and UploadedChunk).

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0002_uploadedfile_summary"),
    ]

    operations = [
        migrations.CreateModel(
            name="UploadSession",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("session_key", models.CharField(blank=True, max_length=100)),
                ("summary", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "chapter",
                    models.ForeignKey(
                        on_delete=models.CASCADE,
                        related_name="upload_sessions",
                        to="quiz.chapter",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="quiz",
            name="upload_session",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=models.SET_NULL,
                related_name="quizzes",
                to="quiz.uploadsession",
            ),
        ),
        migrations.AddField(
            model_name="uploadedfile",
            name="upload_session",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=models.CASCADE,
                related_name="files",
                to="quiz.uploadsession",
            ),
        ),
    ]
