# Generated by Django 5.2.13 on 2026-04-29 03:32

import quiz.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0009_alter_chapter_id_alter_question_id_alter_quiz_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="textbookchunk",
            name="embedding",
            field=quiz.models.VectorEmbedding(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="uploadedchunk",
            name="embedding",
            field=quiz.models.VectorEmbedding(blank=True, null=True),
        ),
    ]
