# Generated by Django 5.2.13 on 2026-05-02 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0015_quizattempt_recommendation_fields"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="uploadsession",
            name="processing_stage",
        ),
        migrations.AlterField(
            model_name="quiz",
            name="error_message",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="quiz",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("processing", "Processing"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                ],
                default="pending",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="quizattempt",
            name="recommendation_error",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="quizattempt",
            name="recommendation_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("processing", "Processing"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                ],
                default="pending",
                max_length=50,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="quizanswer",
            unique_together={("attempt", "question")},
        ),
    ]
