# Generated by Django 5.2.13 on 2026-05-04 04:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0016_remove_uploadsession_processing_stage_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="GenerationMetric",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "generation_type",
                    models.CharField(
                        choices=[
                            ("summary", "Summary"),
                            ("quiz", "Quiz"),
                            ("recommendations", "Recommendations"),
                            ("concept_extraction", "Concept Extraction"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        blank=True,
                        choices=[("minimax", "MiniMax"), ("gemini", "Gemini")],
                        max_length=20,
                    ),
                ),
                ("success", models.BooleanField(default=False)),
                ("duration_ms", models.FloatField(default=0)),
                ("cache_hit", models.BooleanField(default=False)),
                ("error_message", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="textbookchunk",
            name="embedding_version",
            field=models.PositiveSmallIntegerField(
                default=1, help_text="Version of the embedding model/strategy used"
            ),
        ),
        migrations.AddField(
            model_name="textbookchunk",
            name="source_hash",
            field=models.CharField(
                blank=True,
                help_text="MD5 hash of source file for change detection",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="chapter",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="quiz",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="quizanswer",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="quizattempt",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="textbookchunk",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="topic",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="uploadedchunk",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="uploadedfile",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="uploadsession",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AddIndex(
            model_name="textbookchunk",
            index=models.Index(
                fields=["source_title", "embedding_version", "source_hash"],
                name="quiz_textbo_source__c095ec_idx",
            ),
        ),
        migrations.AddField(
            model_name="generationmetric",
            name="related_attempt",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="quiz.quizattempt",
            ),
        ),
        migrations.AddField(
            model_name="generationmetric",
            name="related_session",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="quiz.uploadsession",
            ),
        ),
        migrations.AddIndex(
            model_name="generationmetric",
            index=models.Index(
                fields=["generation_type", "created_at"],
                name="quiz_genera_generat_90eeb4_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="generationmetric",
            index=models.Index(
                fields=["provider", "created_at"], name="quiz_genera_provide_2174dc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="generationmetric",
            index=models.Index(
                fields=["success", "created_at"], name="quiz_genera_success_df104d_idx"
            ),
        ),
    ]
