# Generated by Django 5.2.13 on 2026-05-05 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0017_add_embedding_version_and_source_hash"),
    ]

    operations = [
        migrations.AddField(
            model_name="generationmetric",
            name="output_length",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="generationmetric",
            name="output_validated",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="RetrievalLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("query_text", models.TextField()),
                ("mode", models.CharField(default="quiz", max_length=20)),
                ("retrieved_chunks", models.JSONField(default=list)),
                ("session_chunk_count", models.PositiveIntegerField(default=0)),
                ("textbook_chunk_count", models.PositiveIntegerField(default=0)),
                ("avg_similarity_top_k", models.FloatField(blank=True, null=True)),
                ("min_similarity_top_k", models.FloatField(blank=True, null=True)),
                ("max_similarity_top_k", models.FloatField(blank=True, null=True)),
                ("retrieval_latency_ms", models.FloatField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "upload_session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="retrieval_logs",
                        to="quiz.uploadsession",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["upload_session", "created_at"],
                        name="quiz_retrie_upload__875404_idx",
                    ),
                    models.Index(
                        fields=["mode", "created_at"],
                        name="quiz_retrie_mode_a4e6a7_idx",
                    ),
                    models.Index(
                        fields=["created_at"], name="quiz_retrie_created_58393a_idx"
                    ),
                ],
            },
        ),
    ]
