# Generated by Django 5.2.13 on 2026-05-06 05:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0018_generationmetric_output_length_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="generationmetric",
            name="was_fallback",
            field=models.BooleanField(
                default=False,
                help_text="True if this generation required a fallback to a secondary provider",
            ),
        ),
        migrations.AlterField(
            model_name="generationmetric",
            name="output_validated",
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name="generationmetric",
            name="related_attempt",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="generation_metrics",
                to="quiz.quizattempt",
            ),
        ),
        migrations.AlterField(
            model_name="generationmetric",
            name="related_session",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="generation_metrics",
                to="quiz.uploadsession",
            ),
        ),
    ]
