# Generated by Django 5.2.13 on 2026-05-08 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0019_generationmetric_was_fallback_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="generationmetric",
            index=models.Index(
                fields=["was_fallback"], name="quiz_genera_was_fal_785fb3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="generationmetric",
            index=models.Index(
                fields=["output_validated"], name="quiz_genera_output__411556_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="generationmetric",
            index=models.Index(
                fields=["generation_type", "output_length"],
                name="quiz_genera_generat_8cdc32_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="retrievallog",
            index=models.Index(
                fields=["avg_similarity_top_k"], name="quiz_retrie_avg_sim_5cf04e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="retrievallog",
            index=models.Index(
                fields=["session_chunk_count", "textbook_chunk_count"],
                name="quiz_retrie_session_f8fdec_idx",
            ),
        ),
    ]
