# Generated by Django 5.2.13 on 2026-05-08 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0020_generationmetric_quiz_genera_was_fal_785fb3_idx_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="quiz",
            index=models.Index(fields=["status"], name="quiz_quiz_status_ca9df3_idx"),
        ),
        migrations.AddIndex(
            model_name="quiz",
            index=models.Index(
                fields=["status", "created_at"], name="quiz_quiz_status_e58e60_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="quizattempt",
            index=models.Index(
                fields=["recommendation_status"], name="quiz_quizat_recomme_5464df_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="uploadsession",
            index=models.Index(
                fields=["processing_status"], name="quiz_upload_process_2b764e_idx"
            ),
        ),
    ]
