# Generated by Django 5.2.13 on 2026-05-08 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0021_quiz_quiz_quiz_status_ca9df3_idx_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="question",
            index=models.Index(
                fields=["chapter"], name="quiz_questi_chapter_c5d7c7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="question",
            index=models.Index(fields=["topic"], name="quiz_questi_topic_i_06cf1f_idx"),
        ),
        migrations.AddIndex(
            model_name="question",
            index=models.Index(
                fields=["chapter", "topic"], name="quiz_questi_chapter_69a28b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="textbookchunk",
            index=models.Index(
                fields=["chapter"], name="quiz_textbo_chapter_3390b0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="textbookchunk",
            index=models.Index(
                fields=["chapter", "topic"], name="quiz_textbo_chapter_69dcd0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="uploadedchunk",
            index=models.Index(
                fields=["upload_session"], name="quiz_upload_upload__45701b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="uploadedchunk",
            index=models.Index(
                fields=["upload_session", "chunk_index"],
                name="quiz_upload_upload__8ed657_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="uploadedchunk",
            index=models.Index(
                fields=["chapter"], name="quiz_upload_chapter_d3e8f4_idx"
            ),
        ),
    ]
