# Generated by Django 5.2.13 on 2026-05-08 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0022_question_quiz_questi_chapter_c5d7c7_idx_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="quizanswer",
            index=models.Index(
                fields=["question", "is_correct"], name="quiz_quizan_questio_7ab744_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="uploadedfile",
            index=models.Index(
                fields=["upload_session"], name="quiz_upload_upload__38fb98_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="uploadedfile",
            index=models.Index(
                fields=["upload_session", "chapter"],
                name="quiz_upload_upload__6bde77_idx",
            ),
        ),
    ]
