# Generated by Django 5.2.13 on 2026-05-10 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0023_quizanswer_quiz_quizan_questio_7ab744_idx_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="generationmetric",
            name="quiz_genera_was_fal_785fb3_idx",
        ),
        migrations.RemoveField(
            model_name="generationmetric",
            name="was_fallback",
        ),
        migrations.AlterField(
            model_name="generationmetric",
            name="provider",
            field=models.CharField(
                blank=True, choices=[("deepinfra", "DeepInfra")], max_length=20
            ),
        ),
    ]
