# Generated by Django 5.2.14 on 2026-05-15 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "quiz",
            "0024_remove_generationmetric_quiz_genera_was_fal_785fb3_idx_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="generationmetric",
            name="provider",
            field=models.CharField(
                blank=True, choices=[("deepinfra", "AI Provider")], max_length=20
            ),
        ),
        migrations.AlterField(
            model_name="uploadedfile",
            name="file",
            field=models.FileField(max_length=500, upload_to="uploads/"),
        ),
    ]
