# Generated by Django 5.2.14 on 2026-05-16 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0025_increase_uploadedfile_max_length"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="content_lineage_verified",
            field=models.BooleanField(
                default=False,
                help_text="True if keyword overlap check passed against source chunks",
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="lineage_score",
            field=models.FloatField(
                default=0,
                help_text="Keyword overlap ratio between source chunks and question text",
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="source_chunk_ids",
            field=models.JSONField(
                default=list,
                help_text="UploadedChunk IDs used to generate this question",
            ),
        ),
        migrations.AddField(
            model_name="uploadsession",
            name="summary_lineage_score",
            field=models.FloatField(
                default=0,
                help_text="Keyword overlap ratio between source chunks and summary",
            ),
        ),
        migrations.AddField(
            model_name="uploadsession",
            name="summary_lineage_verified",
            field=models.BooleanField(
                default=False,
                help_text="True if keyword overlap check passed against source chunks",
            ),
        ),
        migrations.AddField(
            model_name="uploadsession",
            name="summary_source_chunk_ids",
            field=models.JSONField(
                default=list, help_text="UploadedChunk IDs used to generate the summary"
            ),
        ),
    ]
